function worldPop(textMsg,pos,color='#fff'){const v=pos.clone().project(camera);if(v.z<-1||v.z>1)return;const el=document.createElement('div');el.className='worldPop';el.textContent=textMsg;el.style.color=color;el.style.left=((v.x*.5+.5)*innerWidth)+'px';el.style.top=((-v.y*.5+.5)*innerHeight)+'px';document.body.appendChild(el);setTimeout(()=>el.remove(),760)}
function showWaveBanner(main,sub=''){const el=$('waveBanner');el.innerHTML=main+(sub?`<div style="font-size:.34em;margin-top:6px;color:#a9cfff;letter-spacing:.12em">${sub}</div>`:'');el.classList.add('show');clearTimeout(el._tm);el._tm=setTimeout(()=>el.classList.remove('show'),1200)}
function clearCampExtras(){for(const o of[...buildPads,...workerObjs,...settlementObjs])if(o.g)scene.remove(o.g);else scene.remove(o);buildPads.forEach(p=>p.labelEl?.remove());buildPads=[];workerObjs=[];settlementObjs=[];wallDecorObjs.forEach(g=>scene.remove(g));wallDecorObjs.clear();turretObjs.forEach(g=>scene.remove(g));turretObjs.clear();flameObjs.forEach(g=>scene.remove(g));flameObjs.clear();warehouseObjs.forEach(g=>scene.remove(g));warehouseObjs.clear();defenseLabelEls.forEach(el=>el.remove());defenseLabelEls.clear();defenseState.clear()}
function makeWorldLabel(){const el=document.createElement('div');el.className='worldLabel';document.body.appendChild(el);return el}
function typeName(t){return t==='wall'?'木柵':t==='turret'?'見張り台':t==='flame'?'火炎塔':'倉庫'}function typeIcon(t){return t==='wall'?'🧱':t==='turret'?'🏹':t==='flame'?'🔥':'📦'}function requiredBaseLevel(type){return type==='wall'||type==='turret'?1:type==='flame'?2:3}function baseUpgradeCost(){return baseLevel===1?{wood:70,coal:20,iron:0}:baseLevel===2?{wood:110,coal:45,iron:0}:baseLevel===3?{wood:150,coal:65,iron:20}:baseLevel===4?{wood:210,coal:90,iron:45}:{wood:999,coal:999,iron:999}}function baseLevelName(){return baseLevel===1?'焚き火':baseLevel===2?'炉付きキャンプ':baseLevel===3?'防衛集落':baseLevel===4?'要塞拠点':'極寒要塞'}
function ensureBaseLabel(){if(baseLabelEl)return;baseLabelEl=document.createElement('div');baseLabelEl.className='baseWorldLabel';document.body.appendChild(baseLabelEl)}
function refreshBaseVisual(){fireGroup.scale.setScalar(1+baseLevel*.12);fireLight.distance=14+baseLevel*4;fireLight.intensity=2+baseLevel*.45;if(baseLevel>=2&&!fireGroup.userData.ring2){const g=new THREE.Group();for(let i=0;i<8;i++){const b=box(.22,.55,.22,0x8d684b),a=i/8*Math.PI*2;b.position.set(Math.cos(a)*1.45,.85,Math.sin(a)*1.45);g.add(b)}fireGroup.add(g);fireGroup.userData.ring2=g}if(baseLevel>=3&&!fireGroup.userData.tower){const g=new THREE.Group(),core=box(1.2,1,1.2,0x8e6848);core.position.y=.7;g.add(core);const roof=box(1.5,.28,1.5,0x53677d);roof.position.y=1.35;g.add(roof);fireGroup.add(g);fireGroup.userData.tower=g}if(baseLevel>=4&&!fireGroup.userData.beacon){const g=new THREE.Group(),mast=box(.22,2.2,.22,0xb4c6d8);mast.position.y=1.7;g.add(mast);const flag=box(.75,.35,.08,0x7ebcff);flag.position.set(.38,2.55,0);g.add(flag);fireGroup.add(g);fireGroup.userData.beacon=g}if(baseLevel>=5&&!fireGroup.userData.crown){const g=new THREE.Group();for(let i=0;i<4;i++){const p=box(.16,1.25,.16,0xd6ecff),a=i/4*Math.PI*2;p.position.set(Math.cos(a),2,Math.sin(a));g.add(p)}const crown=box(2.35,.18,2.35,0xffd979);crown.position.y=2.72;g.add(crown);fireGroup.add(g);fireGroup.userData.crown=g}}
function upgradeBase(){if(baseLevel>=5)return false;const c=baseUpgradeCost();if(wood<c.wood||coal<c.coal||iron<c.iron)return false;wood-=c.wood;coal-=c.coal;iron-=c.iron;baseLevel++;baseUpgradeProgress=0;baseMax+=120;baseHP=baseMax;fuel=Math.min(100,fuel+35);moveSpeed*=1.04;playerDmg=Math.round(playerDmg*1.08);if(baseLevel>=2){ensureWorkers();wood+=20}if(baseLevel>=3){warehouseBonus+=25;coal+=15}refreshBaseVisual();updateCampVisual();updateHUD();sfx('base');showWaveBanner('🏰 BASE Lv.'+baseLevel,baseLevelName()+' / 新エリア解放');worldPop('拠点 Lv.'+baseLevel,new THREE.Vector3(0,3.2,0),'#ffd98b');return true}
function updateBaseUpgrade(dt){if(phase!=='day'||baseLevel>=5)return;const d=Math.hypot(pPos.x,pPos.z);if(d>2.8){baseUpgradeProgress=0;return}const c=baseUpgradeCost();if(wood>=c.wood&&coal>=c.coal&&iron>=c.iron){baseUpgradeProgress+=dt;if(baseUpgradeProgress>.65)upgradeBase()}else baseUpgradeProgress=0}
function updateBaseLabel(){ensureBaseLabel();if(baseLevel>=5)baseLabelEl.innerHTML='🏰 '+baseLevelName()+' Lv.MAX';else{const c=baseUpgradeCost(),ready=wood>=c.wood&&coal>=c.coal;baseLabelEl.className='baseWorldLabel'+(ready?' ready':'');baseLabelEl.innerHTML='🏰 '+baseLevelName()+' Lv.'+baseLevel+' → '+(baseLevel+1)+'<span class="cost">🌲'+c.wood+'　🪨'+c.coal+(c.iron?'　⚙️'+c.iron:'')+'</span>'}projectLabel(baseLabelEl,new THREE.Vector3(0,3.05,0),phase==='day'&&Math.hypot(pPos.x,pPos.z)<8.5)}
function initAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();masterGain.gain.value=.22;masterGain.connect(audioCtx.destination)}
function tone(freq=440,dur=.08,type='sine',vol=.13,slide=1){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*slide),audioCtx.currentTime+dur);g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(masterGain);o.start();o.stop(audioCtx.currentTime+dur)}
function sfx(name){if(!audioCtx)return;const now=performance.now();if(lastSfx[name]&&now-lastSfx[name]<45)return;lastSfx[name]=now;if(name==='wood'){tone(170,.06,'square',.08,1.8);tone(280,.08,'triangle',.06,1.3)}else if(name==='coal'){tone(110,.09,'square',.09,.72);tone(190,.05,'triangle',.05,.8)}else if(name==='iron'){tone(520,.05,'triangle',.06,1.3);tone(780,.09,'sine',.05,1.1)}else if(name==='build'){tone(180,.09,'square',.08,1.3);setTimeout(()=>tone(330,.12,'triangle',.09,1.45),70)}else if(name==='upgrade'){tone(330,.08,'triangle',.08,1.3);setTimeout(()=>tone(520,.1,'triangle',.08,1.25),70);setTimeout(()=>tone(780,.14,'sine',.07,1.05),145)}else if(name==='shoot')tone(760,.035,'square',.025,.72);else if(name==='flame')tone(125,.12,'sawtooth',.035,.55);else if(name==='kill'){tone(210,.05,'square',.05,1.8);tone(420,.07,'triangle',.04,1.25)}else if(name==='wave'){tone(105,.3,'sawtooth',.09,.65);setTimeout(()=>tone(85,.35,'sawtooth',.08,.55),160)}else if(name==='base'||name==='capture'||name==='rescue'){tone(392,.1,'triangle',.08,1.2);setTimeout(()=>tone(587,.12,'triangle',.08,1.2),90);setTimeout(()=>tone(784,.18,'sine',.07,1.05),190)}else if(name==='boss'){tone(70,.45,'sawtooth',.12,.55);setTimeout(()=>tone(55,.55,'square',.09,.5),240)}}
function makeGroundTag(title,sub='',accent='#ffd36b',w=2.8,h=.82){const cv=document.createElement('canvas');cv.width=512;cv.height=160;const ctx=cv.getContext('2d'),tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;tex.minFilter=THREE.LinearFilter;const mat=new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide}),m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),mat);m.rotation.x=-Math.PI/2;m.position.y=.075;m.renderOrder=3;m.userData={cv,ctx,tex,last:''};scene.add(m);groundTagMeshes.push(m);setGroundTag(m,title,sub,accent);return m}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):ctx.rect(x,y,w,h)}
function setGroundTag(m,title,sub='',accent='#ffd36b'){if(!m)return;const sig=title+'|'+sub+'|'+accent;if(m.userData.last===sig)return;m.userData.last=sig;const{cv,ctx,tex}=m.userData;ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='rgba(5,16,31,.82)';roundRect(ctx,8,8,496,144,28);ctx.fill();ctx.strokeStyle=accent;ctx.lineWidth=5;ctx.stroke();ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 43px sans-serif';ctx.fillText(title,256,67);ctx.fillStyle=accent;ctx.font='800 31px sans-serif';ctx.fillText(sub,256,119);tex.needsUpdate=true}
function clearGroundTags(){groundTagMeshes.forEach(m=>scene.remove(m));groundTagMeshes=[]}
function baseGroundText(){const c=baseUpgradeCost();return baseLevel>=5?['🏰 '+baseLevelName()+' Lv.MAX','DAY 7 BOSS']:['🏰 Lv.'+baseLevel+' → '+(baseLevel+1),'🌲'+c.wood+'  🪨'+c.coal+(c.iron?'  ⚙️'+c.iron:'')]}
let baseGroundTag=null;function ensureBaseGroundTag(){if(!baseGroundTag){baseGroundTag=makeGroundTag('🏰 Lv.1 → 2','🌲70  🪨20','#ffd36b',3.35,.9);baseGroundTag.position.set(0,.08,2.25)}const t=baseGroundText();setGroundTag(baseGroundTag,t[0],t[1],'#ffd36b')}
function outpostInfo(type){return type==='sawmill'?{name:'製材所',icon:'🪵',color:0xffc66e,need:2,prod:'🌲 +6'}:type==='coalmine'?{name:'炭鉱',icon:'⛏️',color:0xaec8ea,need:2,prod:'🪨 +4'}:type==='ironmine'?{name:'鉄鉱山',icon:'⚙️',color:0xcfd8e2,need:3,prod:'⚙️ +2'}:type==='survivor'?{name:'生存者キャンプ',icon:'🧑',color:0x9de3a0,need:2,prod:'住民 +1'}:{name:'研究所跡地',icon:'🔬',color:0x9ed7ff,need:4,prod:'全塔 +10%'}}
function makeOutpostVisual(type,x,z){const g=new THREE.Group(),floor=box(3,.12,3,0x6e7e8e);floor.position.y=.58;g.add(floor);if(type==='sawmill')addVoxelDetails(g,[[2.3,.65,1.2,0x8f6339,0,1,0],[2.55,.18,1.45,0x594438,0,1.48,0],[.28,1.05,.28,0xd4ad6d,-.95,1.2,.55],[.28,1.05,.28,0xd4ad6d,.95,1.2,.55],[1.6,.18,.18,0xc98b4e,0,.78,-.85]]);else if(type==='coalmine'||type==='ironmine')addVoxelDetails(g,[[2.2,1.55,.5,0x545f6c,0,1.25,0],[.4,1.3,.4,0x9ca9b5,-.88,1.35,0],[.4,1.3,.4,0x9ca9b5,.88,1.35,0],[1.65,.25,.25,type==='ironmine'?0xc9d2da:0x303843,0,.85,.55],[.4,.4,.4,type==='ironmine'?0xd9e2e9:0x252b32,-.55,.85,-.65],[.4,.4,.4,type==='ironmine'?0xaab6c0:0x3a414b,.2,.85,-.7]]);else if(type==='survivor')addVoxelDetails(g,[[2.2,.65,1.5,0xb66e48,0,1,0],[2.45,.18,1.7,0xe1b36b,0,1.47,0],[.25,.7,.25,0xffd36b,.8,1.2,.65],[.7,.12,.08,0xfff0a0,.8,1.62,.65]]);else addVoxelDetails(g,[[2,1.3,1.8,0x687b8f,0,1.3,0],[2.3,.22,2.05,0x3c5268,0,2.03,0],[.35,.75,.35,0x9ed7ff,-.55,2.35,0],[.35,.75,.35,0x9ed7ff,.55,2.35,0]]);g.position.set(x,0,z);scene.add(g);return g}
function initOutposts(){outposts.forEach(o=>{scene.remove(o.g);if(o.tag)scene.remove(o.tag)});outposts=[];[['sawmill',-19,-10],['coalmine',19,-9],['ironmine',0,21],['survivor',-18,17],['research',18,17]].forEach(([type,x,z])=>{const i=outpostInfo(type),g=makeOutpostVisual(type,x,z),tag=makeGroundTag(i.icon+' '+i.name,'🔒 拠点Lv.'+i.need,'#8ea6bd',3.25,.88);tag.position.set(x,.08,z+2.15);outposts.push({type,x,z,g,tag,captured:false,hp:240,maxHp:240,progress:0,prodT:0})})}
function refreshOutpostTag(o){const i=outpostInfo(o.type);if(o.captured)setGroundTag(o.tag,i.icon+' '+i.name+' ✓',i.prod+' / HP '+Math.max(0,o.hp|0),'#86f0b1');else if(baseLevel<i.need)setGroundTag(o.tag,i.icon+' '+i.name,'🔒 拠点Lv.'+i.need,'#8ea6bd');else setGroundTag(o.tag,i.icon+' '+i.name,'近づいて確保 / '+i.prod,'#ffd36b')}
function updateOutposts(dt){for(const o of outposts){refreshOutpostTag(o);if(phase!=='day')continue;const d=Math.hypot(o.x-pPos.x,o.z-pPos.z);if(!o.captured&&baseLevel>=outpostInfo(o.type).need&&d<2.4){o.progress+=dt;if(o.progress>.7){o.progress=0;o.captured=true;o.hp=o.maxHp;sfx('capture');showWaveBanner('AREA SECURED',outpostInfo(o.type).name+' を確保');if(o.type==='survivor'){rescued++;makeWorker(workerObjs.length)}if(o.type==='research'){turretDmg=Math.round(turretDmg*1.1);playerDmg=Math.round(playerDmg*1.08)}}}else if(!o.captured)o.progress=0;if(o.captured){o.prodT-=dt;if(o.prodT<=0){o.prodT=4.2;if(o.type==='sawmill'){wood+=6;sfx('wood')}else if(o.type==='coalmine'){coal+=4;sfx('coal')}else if(o.type==='ironmine'){iron+=2;sfx('iron')}updateHUD()}}}}
function activeOutposts(){return outposts.filter(o=>o.captured&&o.hp>0)}function damageOutpost(o,dmg){o.hp-=dmg;if(o.hp<=0){o.hp=0;o.captured=false;o.progress=0;showWaveBanner('OUTPOST LOST',outpostInfo(o.type).name+' が陥落')}}
function chooseNightModifier(){const pool=day<=2?['normal','wolf']:['blizzard','wolf','fuel','armored','siege'];if(day===6)pool.push('bossOmen');nightModifier=pool[Math.floor(Math.random()*pool.length)];const map={normal:['静かな夜','通常襲撃'],blizzard:['猛吹雪','見張り台射程 -25%'],wolf:['狼の夜','高速の狼が大量出現'],fuel:['燃料危機','燃料消費 +70%'],armored:['重装襲来','高耐久兵が増加'],siege:['破城の夜','防壁狙いが増加'],bossOmen:['巨大な足跡','次夜にボス襲来']};return map[nightModifier]}