import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { Script } from "node:vm";
export const sources = [
  "state",
  "world",
  "voxel-style",
  "audio",
  "effects",
  "feedback",
  "base",
  "outposts",
  "buildings",
  "player",
  "enemies",
  "resources",
  "ui",
  "ground-ui",
  "construction",
  "input",
  "game",
  "bootstrap",
];
const text =
  '// Generated by npm run build. Edit src/, never this bundle.\n(()=>{\n"use strict";\n' +
  sources
    .map(
      (name) =>
        "\n// ---- " +
        name +
        " ----\n" +
        readFileSync(
          new URL("../src/" + name + ".js", import.meta.url),
          "utf8",
        ),
    )
    .join("\n") +
  "\n})();\n";
new Script(text, { filename: "game.js" });
mkdirSync(new URL("../dist/", import.meta.url), { recursive: true });
writeFileSync(new URL("../dist/game.js", import.meta.url), text);
console.log("Built " + sources.length + " source files; syntax valid.");
